# Generated by Django 5.2.11 on 2026-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_chat_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidecision',
            name='decision_type',
            field=models.CharField(choices=[('prioritization', 'Priorisation'), ('reminder', 'Rappel'), ('postpone_suggestion', 'Suggestion report'), ('risk_alert', 'Alerte risque'), ('focus_mode', 'Mode focus'), ('chat', 'Chat')], max_length=50),
        ),
    ]
